// <auto-generated />
using System;
using Book_Management.Infrastructure.Persistense;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Book_Management.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250223152002_SeedData12255121")]
    partial class SeedData12255121
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Book_Management.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublicationYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d290f1ee-6c54-4b01-90e6-d701748f0851"),
                            Author = "F. Scott Fitzgerald",
                            CreatedAt = new DateTime(2025, 2, 23, 15, 20, 1, 599, DateTimeKind.Utc).AddTicks(3313),
                            IsDeleted = false,
                            PublicationYear = new DateTime(1925, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Great Gatsby",
                            ViewCount = 100
                        },
                        new
                        {
                            Id = new Guid("f29b7a7b-4e1d-4f3d-b6b1-85d3e2486e2b"),
                            Author = "George Orwell",
                            CreatedAt = new DateTime(2025, 2, 23, 15, 20, 1, 599, DateTimeKind.Utc).AddTicks(3329),
                            IsDeleted = false,
                            PublicationYear = new DateTime(1949, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "1984",
                            ViewCount = 200
                        },
                        new
                        {
                            Id = new Guid("9b2f74e2-cf32-42bb-8c39-5f8f658a3b99"),
                            Author = "Harper Lee",
                            CreatedAt = new DateTime(2025, 2, 23, 15, 20, 1, 599, DateTimeKind.Utc).AddTicks(3332),
                            IsDeleted = false,
                            PublicationYear = new DateTime(1960, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "To Kill a Mockingbird",
                            ViewCount = 150
                        },
                        new
                        {
                            Id = new Guid("3c1a2e3d-77d5-4e9c-a2b5-0b5c9d7e2f3a"),
                            Author = "Jane Austen",
                            CreatedAt = new DateTime(2025, 2, 23, 15, 20, 1, 599, DateTimeKind.Utc).AddTicks(3335),
                            IsDeleted = false,
                            PublicationYear = new DateTime(1813, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pride and Prejudice",
                            ViewCount = 180
                        },
                        new
                        {
                            Id = new Guid("e45a8b9a-5f13-4e59-8a6b-4e8d2f6a3b2d"),
                            Author = "Herman Melville",
                            CreatedAt = new DateTime(2025, 2, 23, 15, 20, 1, 599, DateTimeKind.Utc).AddTicks(3337),
                            IsDeleted = false,
                            PublicationYear = new DateTime(1851, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Moby-Dick",
                            ViewCount = 90
                        },
                        new
                        {
                            Id = new Guid("a1f4c3e6-8b4f-4c6e-b5a4-2e8b6c3f1d2a"),
                            Author = "J.D. Salinger",
                            CreatedAt = new DateTime(2025, 2, 23, 15, 20, 1, 599, DateTimeKind.Utc).AddTicks(3339),
                            IsDeleted = false,
                            PublicationYear = new DateTime(1951, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Catcher in the Rye",
                            ViewCount = 220
                        },
                        new
                        {
                            Id = new Guid("6d9f2b4e-3a4c-4d5e-9a8b-2c6f3b1e8d4a"),
                            Author = "J.R.R. Tolkien",
                            CreatedAt = new DateTime(2025, 2, 23, 15, 20, 1, 599, DateTimeKind.Utc).AddTicks(3347),
                            IsDeleted = false,
                            PublicationYear = new DateTime(1954, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lord of the Rings",
                            ViewCount = 300
                        },
                        new
                        {
                            Id = new Guid("b4e6f9a2-3c1d-4e5b-9a8f-6c3b2d1a4e8b"),
                            Author = "Aldous Huxley",
                            CreatedAt = new DateTime(2025, 2, 23, 15, 20, 1, 599, DateTimeKind.Utc).AddTicks(3349),
                            IsDeleted = false,
                            PublicationYear = new DateTime(1932, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Brave New World",
                            ViewCount = 170
                        });
                });

            modelBuilder.Entity("Book_Management.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d290f1ee-6c54-4b01-90e6-d701748f0851"),
                            CreatedAt = new DateTime(2025, 2, 23, 15, 20, 1, 599, DateTimeKind.Utc).AddTicks(3490),
                            Email = "Muhammadali@gmail.com",
                            IsDeleted = false,
                            Name = "Muhammadali",
                            Password = "$2a$11$aYwD4DgvmJtKUeoK4W3bX.mFV4LLpzoPXRN6b2Uy5WLH09giLjqca",
                            PhoneNumber = "+998900206000",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("f29b7a7b-4e1d-4f3d-b6b1-85d3e2486e2b"),
                            CreatedAt = new DateTime(2025, 2, 23, 15, 20, 1, 729, DateTimeKind.Utc).AddTicks(4763),
                            Email = "alisher@gmail.com",
                            IsDeleted = false,
                            Name = "Alisher",
                            Password = "$2a$11$M3ErFQwilq0Iucvqk2inaOnOJ29E2/toAGYFcpKeamWmG2zFYHwlC",
                            PhoneNumber = "+998900205000",
                            Role = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
